### ISSUE TITLE
WHWHspace Task-1

### ISSUE THREAD

**Issue by MontyPan** [DatacomRD/FlowTraining#1]
請閱讀這份文件：https://github.com/DatacomRD/FlowTraining/blob/master/README.md

這個 training 就是要實踐文件中的工作流程、以及審視你對於作業規範的遵守程度。

第一個 task 的內容請參閱：https://github.com/DatacomRD/FlowTraining/blob/master/task/Task-1.md

要實作的內容是「Github」段落的步驟，而實作過程當中需要先學會 Markdown 與 Git。

有任何問題可以在這個 issue 下提問。

**Comment by MontyPan** [comment]
### 需求追加

如果你不是處在 full time 在做 training 的情況（aka 你同時要處理指派的其他任務），請在 pull request（以及後續用來 notify reviewer 的 comment 當中）寫明你花了多少時間製造出這些 commit。

此需求追加適用於 training 階段的所有 task

**Comment by WHWHspace** [comment]
感谢指出global username和email的问题。

1.我是应该在原来fork的基础上修改吗？
2.我新建的task-1.md应该放在那个目录下？

**Comment by MontyPan** [comment]
> 我是应该在原来fork的基础上修改吗？

施主，這個問題應該要問你自己。上至老闆下至主管，大家通常都只看結果而不太管過程。

再者，你這個問題曝露出你對 git 的本質不甚理解。最根本的問題在於：這個 branch 作壞了，對 master branch 或是（你的）整個 repo 有什麼影響嗎？答案是沒有，而且「對整個 repo 會不會有影響」這個問題根本沒意義...... :sleepy: 

然後，念在這是我們初次交手（？），再提點你一個：「如果隨時都可以設定 user.name 跟 user.email，那麼是不是代表了 user.name 跟 user.email 是 commit by commit 的重新給值？」

寫到這邊就發現... 你可能漏掉一個 git config 的事實：git config 有三個 scope：system、global、repo，然後優先順序是遞增的。最簡單的說法是：你可以在 repo A 叫 `foo`、用 `foo@foo.com` 這個 email，在 repo B 叫 `wtf`、用 `wtf@wtf.org`。

> 我新建的task-1.md应该放在那个目录下？

沒有寫清楚、你怎麼搞都不會是你的問題（當然，你要把 `/task/Task-1.md` 給蓋過去我也...... :scream: ）。

當然，人有失神馬有失蹄，說不定是我該註明路徑卻漏掉了。所以感謝你問這個問題，但是我是故意不寫的...... [奸笑]

**Comment by MontyPan** [comment]
忘記用 commit close issue 了...... (艸
