### ISSUE TITLE
josephwindows Task-1

### ISSUE THREAD

**Issue by MontyPan** [DatacomRD/FlowTraining#19]
請閱讀這份文件：https://github.com/DatacomRD/FlowTraining/blob/master/README.md

這個 training 就是要實踐文件中的工作流程、以及審視你對於作業規範的遵守程度。

第一個 task 的內容請參閱：https://github.com/DatacomRD/FlowTraining/blob/master/task/Task-1.md

要實作的內容是「Github」段落的步驟，而實作過程當中需要先學會 Markdown 與 Git。

有任何問題可以在這個 issue 下提問。

**Comment by josephwindows** [comment]
請問 Markdown training文件是要commit到FlowTraining嗎?

**Comment by MontyPan** [comment]
我看不太懂何謂「Markdown training 文件」？ https://github.com/DatacomRD/FlowTraining/blob/master/task/Task-1.md 當中應該沒有定義這個詞，所以我不懂你說的是什麼。

Task-1 的確有要產出文件、自然是要用 commit 的方式搭配 git 操作讓你產生出來的文件進到 `FlowTraining` 這個 repo。

**Comment by josephwindows** [comment]
謝謝! 我已經知道了!
但是, 我找不到markdown中要如何使用table?
可以請教一下嗎?

**Comment by MontyPan** [comment]
請詳閱 https://github.com/DatacomRD/FlowTraining/blob/master/task/Task-1.md

**Comment by josephwindows** [comment]
我無法clone FlowTraining
$git clone https://github.com/DatacomRD/FlowTraining.git
fatal: could not create work tree dir 'FlowTraining':Permission denied

**Comment by josephwindows** [comment]
已經可以clone了
