### ISSUE TITLE
keanudatacom Task-1

### ISSUE THREAD

**Issue by MontyPan** [DatacomRD/FlowTraining#20]
請閱讀這份文件：https://github.com/DatacomRD/FlowTraining/blob/master/README.md

這個 training 就是要實踐文件中的工作流程、以及審視你對於作業規範的遵守程度。

第一個 task 的內容請參閱：https://github.com/DatacomRD/FlowTraining/blob/master/task/Task-1.md

要實作的內容是「Github」段落的步驟，而實作過程當中需要先學會 Markdown 與 Git。

有任何問題可以在這個 issue 下提問。

**Comment by ghost** [comment]
在公司要使用的 github account 是 keanudatacom。
請問 reject 的原因是因為我誤用了keanucode 進行 Task-1 嗎？
如果是我會使用 keanudatacom 重新進行一次, 謝謝。

**Comment by MontyPan** [comment]
我想 #22 的 comment 已經講得很清楚了

> **另外**，你 commit 的時候用的是...  （後略）
