### ISSUE TITLE
JanasLeeD Task-1

### ISSUE THREAD

**Issue by MontyPan** [DatacomRD/FlowTraining#41]
請閱讀這份文件：https://github.com/DatacomRD/FlowTraining/blob/master/README.md

這個 training 就是要實踐文件中的工作流程、以及審視你對於作業規範的遵守程度。

第一個 task 的內容請參閱：https://github.com/DatacomRD/FlowTraining/blob/master/task/Task-1.md

要實作的內容是「Github」段落的步驟，而實作過程當中需要先學會 Markdown 與 Git。

有任何問題可以在這個 issue 下提問。

**Comment by JanasLeeD** [comment]
已經收到mail 並依指示，開始學習 Markdown 語法。
感謝!

**Comment by JanasLeeD** [comment]
已經製作自我介紹

**Comment by MontyPan** [comment]
這邊（issue）是用來問問題 or 溝通的、不是用來回報進度的。有沒有進度看 PR 就知道了。所以你上一個 comment 是多餘的，請不要浪費時間在這類的事情上。
